source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’
use_frameworks!

target ‘inloop_task’ do
	pod 'Alamofire', '~> 4.4'
    	pod 'Sync', '~> 3'
    	pod 'DATASource', '~> 6'
	pod 'Swinject', '~> 2'
    	pod 'SwinjectStoryboard', '~> 1'
	pod 'SwinjectAutoregistration', '~> 2'
end